import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { useRouter } from 'next/router'
import car2 from '../public/car2.jpeg'
import { getSession, signIn, signOut } from 'next-auth/client'


export const getServerSideProps = async (context) => {
  const session = await getSession(context);
  return {
    props: {
      session,
    },
  }
}

export default function Home({session}) {


// Expected output: "The quick brown fox jumps over the lazy monkey. If the dog reacted, was it really lazy?"


  return (
    <>
      <Head>
        <title>Myapp</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous"/>
      </Head>
      <main className={styles.main}>
        
        {
          session ? 
            <button onClick={()=> signOut()}>accountdan ciqish</button> :
            <button onClick={()=> signIn()}>accountga kirish</button>
        }

        {
          session && (
            <>
            <h1>{ session.user.email}</h1>
              <h1>{session.user.name}</h1>
              <img src={session.user.image} alt={session.user.name} />
            </>
            )
        }

        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />
          <div className={styles.thirteen}>
            <Image
              src="/thirteen.svg"
              alt="13"
              width={40}
              height={31}
              priority
            />

           
          </div>
        </div>

        
      </main>
      <Image
              src={car2}
              width={800}
              height={400}
              alt='rasml'
                placeholder="blur"
              />
    </>
  )
}
